require_relative '../node_modules/react-native-macos/scripts/react_native_pods'

platform :macos, '27.0'
ENV['RCT_NEW_ARCH_ENABLED'] = '1'
prepare_react_native_project!
project 'UnwiredMail', 'Debug' => :debug, 'Release' => :release, 'Testing' => :release

target 'UnwiredMail' do
  pod 'GoogleSignIn', '10.0.0'
  config = use_native_modules!
  expected = File.realpath('../node_modules/react-native-macos')
  raise 'Autolinking resolved a foreign React Native host' unless File.realpath(config[:reactNativePath]) == expected
  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  post_install do |installer|
    react_native_post_install(installer, '../node_modules/react-native-macos')
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |configuration|
        configuration.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '27.0'
      end
    end
  end
end
